mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
	path('', views.index, name='index'),
    #path('<int:pk>/', views.DetailView.as_view(), name='detail'),
	path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
	path('<int:question_id>/vote/', views.vote, name='vote'),
	path('test', views.test_celery),
	path('register', views.register, name='register'),
	path('<int:data_id>/', views.detailRegister, name='registerDetail')
]

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')

	def __str__(self):
		return self.question_text

	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):
		 return self.choice_text

class User(models.Model):
	author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
	title = models.CharField(max_length=200)
	text = models.TextField()
	created_date = models.DateTimeField(default=timezone.now)
	published_date = models.DateTimeField(blank=True, null=True)

	def publish(self):
		self.published_date = timezone.now()
		self.save()

	def __str__(self):
		return self.title

class RegisterModel(models.Model):
	register = models.ForeignKey('auth.User', on_delete=models.CASCADE)
	filepath = models.CharField(max_length=200)
	module = models.TextField()
	created_date = models.DateTimeField(default=timezone.now)
# Create your models here.

mysite/polls/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse, render_to_response, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from subprocess import call
from .models import Choice, Question, RegisterModel
import subprocess
import json

from polls import tasks

def test_celery(request):
	result = tasks.setCommnadOrder.delay()

	response_data = {}
	response_data['result'] = 'success'
	response_data['message'] = 'start'
	return HttpResponse(json.dumps(response_data), content_type="application/json")

def index(request):
	#	setCommnadOrder()
	latest_question_list = Question.objects.order_by('-pub_date')[:5]
	context = {'latest_question_list': latest_question_list}
	return render(request, 'polls/index.html', context)

def register(request):
	latest_data =RegisterModel.objects.order_by('-created_date')[:5]
	context = {'latest_data' : latest_data}
	return render(request, 'polls/register.html', context)

def detailRegister(request, data_id):
    registerModel = get_object_or_404(RegisterModel, pk=data_id)
    return render(request, 'polls/registerDetail.html', {'registerModel': registerModel})

class DetailView(generic.DetailView):
	model = Question
	template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
	model = Question
	template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def setCommnadOrder():
	tmp = call('pwd')
	print(tmp)
	#makeFilebeat('filebeats.yml')
	#call('./filebeat run')
	#command = './filebeat run -d "publish"'
	command = 'nohup ./filebeat -e -d "publish"'
	subprocess.check_call(command.split())

def makeFilebeat(beatName):
	_beatName = beatName;
	print(_beatName);
	fw = open(_beatName, 'w')
	fw.write('filebeat.inputs:\n')
	fw.write('enabled: true\n')
	fw.write('paths:\n')
	fw.write('	- type: log\n')
	fw.write('	- /var/log/*.log\n')
	fw.write('output.elasticsearch:\n')
	fw.write(' hosts: ["localhost:9200"]\n')
	fw.close();

mysite/polls/templates/polls/detail.html
{% load static %}

<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">


<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>
<button type="button" onclick="JavaScript:startFunction()" id="start" class="btn btn-primary">start</button>
<iframe src="http://localhost:5601/app/kibana#/dashboard/Filebeat-MySQL-Dashboard?_g=()" width="1000px" height="800"></iframe>

mysite/polls/templates/polls/foo.html
<!DOCTYPE html>
<html>
<head>
<script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
<script type="text/javascript">
$(function() {
  var count = 0;
  $('#mybutton').click(function() {
      $.get('/ajx/mygetview', {'mydata': 'xyz'}, function(data) {
        $('#output').html(data); // append to inner html
        //alert(data);
    });
  });
  $('#mybutton2').click(function() {
      // You gotta include the csrf_token in your post data
      $.post('/ajx/mypostview', {'mydata': 'xyz', 'csrfmiddlewaretoken': '{{ csrf_token }}'}, function(data) {
        $('#output').html(data); // append to inner html
        //alert(data);
    });
  });

  $('#mybutton3').click(function(event) {
      // You gotta include the csrf_token in your post data
    event.preventDefault();
    $.ajax({
        type: 'POST',
        url: '/ajx/myajaxview',
        data: {'mydata': 'xyz', 'csrfmiddlewaretoken': '{{ csrf_token }}'},
        success: function (data, textStatus) {
            //alert(data, textStatus);
            $('#output').html(data); // append to inner html
        },
        error: function(xhr, status, e) {
            alert(status, e);
        }
    });
  });

  $('#myform').submit(function(event) {
    // You gotta include the csrf_token in your post data
    event.preventDefault();
    $.ajax({
        type: 'POST',
        url: '/ajx/myajaxformview',
        dataType: 'json',
        data: $('#myform').serialize(), // serialize all your
        success: function (data, textStatus) {
            //alert(JSON.stringify(data), textStatus);
            count += 1;
            $('#output2').html("");
            $('#output2').html(count + " - You sent a ajax form post. Here's the data from server" + JSON.stringify(data)); // append to inner html
        },
        error: function(xhr, status, e) {
            alert(status, e);
        }
    });
  });

});
</script>
</head>
<body>
  <button id="mybutton"> Click me - GET </button>
  <button id="mybutton2"> Click me - POST </button>
  <button id="mybutton3"> Click me - AJAX </button>
  <div id="output"></div>

<br />
<br />

  <form id="myform" method="post" action="/rango/login/">
    {% csrf_token %}
    Field1: <input type="text" name="field1" value="" size="50" />
    <br />
    Field2: <input type="text" name="field2" value="" size="50" />
    <br />

    <input type="submit" value="Click me- AJAX form" /></input>
  </form>
  <div id="output2"></div>

</body>
</html>

mysite/polls/templates/polls/index.html
{% load static %}

<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<script>
  function startFunction()
  {
    $.ajax({
      url: "/polls/test",
      data: {
      },
      success: function( result ) {
        alert('start')
      },
      error:function(err)
      {
        alert('error')
      }
    })
  }
</script>


{% if latest_question_list %}
    <div class="list-group">
    {% for question in latest_question_list %}
        <a class="list-group-item list-group-item-action" href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
    {% endfor %}
  </div>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<button type="button" onclick="JavaScript:startFunction()" id="start" class="btn btn-primary">start</button>

mysite/polls/templates/polls/register.html
{% load static %}

<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<script>
  function startFunction()
  {
    $.ajax({
      url: "/polls/test",
      data: {
      },
      success: function( result ) {
        alert('start')
      },
      error:function(err)
      {
        alert('error')
      }
    })
  }
</script>


{% if latest_data %}
    <div class="list-group">
    {% for data in latest_data %}
        <a class="list-group-item list-group-item-action" href="{% url 'polls:registerDetail' data.id %}">{{ data.register }} : {{ data.filepath }}</a>
    {% endfor %}
  </div>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<button type="button" onclick="JavaScript:startFunction()" id="start" class="btn btn-primary">start</button>

mysite/polls/templates/polls/registerDetail.html
{% load static %}

<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">


<h1>{{ registerModel.register }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div class="card" style="width: 18rem;">
  <ul class="list-group list-group-flush">
    <li class="list-group-item">{{registerModel.filepath}}</li>
    <li class="list-group-item">{{registerModel.module}}</li>
    <li class="list-group-item">{{registerModel.created_date}}</li>
  </ul>
</div>


<button type="button" onclick="JavaScript:startFunction()" id="start" class="btn btn-primary">start</button>
<iframe src="http://localhost:5601/app/kibana#/dashboard/Filebeat-MySQL-Dashboard?_g=()" width="1000px" height="800"></iframe>

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>